name: Build, package and push docs OCI image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docs/**
      - .github/workflows/publish-docs.yml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-push:
    name: Build and push www site
    uses: codesmithcloud/ci/.github/workflows/multi-platform-oci-build.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    with:
      context: ./docs
      name: codesmithcloud/replik8s-docs
